=pod

=head1 NAME

lane

=head1 SYNOPSIS

Visualizations for the Bill Lane Center for the West, Stanford University.
Fall 2010.

=head1 DESCRIPTION

The files now are simply a reflection of the current work by Nandu for the lane center. More organization to come as the project gets bigger.

=head1 BUGS

You better believe it.

=head1 Seeing Visualizations

Just load up the html file(s) present in a browser to check out the results.

=head1 CONTRIBUTING

Too early to be accepting any contributions. Just using github to collaborate and distribute for now.
 
=head1 SEE ALSO

Yinfeng's github.

west.stanford.edu

=head1 AUTHORS

Yinfeng Qin

Geoff McGhee

Nandu Jayakumar (firstname@univ.edu)

=cut

