=pod

=head1 NAME

lane

=head1 SYNOPSIS

Visualizations for the Bill Lane Center for the West, Stanford University.
Fall 2010.

=head1 DESCRIPTION

This simple visualization provides information about some major rivers
in California along with the streamflow information attached to them
over a period of time.

=head1 BUGS

You better believe it.

=head1 License/Copyright

See LICENSE

=head1 Documentation/Source Code

github.com/junkumar/lane

=head1 Building/Installing

After placing a SQLite file in the directory with the right data, run
makeJSON.pl to generate data.js.

Simply copy the entire directory including data.js to install on a
webserver or locally.

=head1 Seeing Visualizations

Just load up the html file(s) present in a browser to check out the results.

=head1 CONTRIBUTING

Too early to be accepting any contributions. Just using github to collaborate and distribute for now.
 
=head1 SEE ALSO

Yinfeng's github.

west.stanford.edu

=head1 AUTHORS

Yinfeng Qin

Geoff McGhee

Nandu Jayakumar (firstname@univ.edu)

=cut

